plugin.plugin_configuration.search_api_processor.glossary:
  type: search_api.fields_processor_configuration
  label: 'Glossary configuration'
  mapping:
    glossarytable:
      type: string
    field_enabled:
      type: integer
    weights:
      type: mapping
      mapping:
        preprocess_index:
          type: integer
    grouping_defaults:
      type: mapping
      mapping:
        grouping_other:
          type: string
        grouping_az:
          type: integer
        grouping_09:
          type: integer

facet.widget.config.glossaryaz:
  type: facet.widget.default_config
  label: 'Glossary widget configuration'
  mapping:
    show_count:
      type: integer
    enable_default_theme:
      type: integer

mukurtu_dictionary_glossary_order.settings:
  type: config_object
  label: 'Dictionary Glossary Order Settings'
  mapping:
    sort_mode:
      type: string
      label: 'Sort mode'
    weights:
      type: sequence
      label: 'Glossary entry weights'
      sequence:
        type: mapping
        mapping:
          glossary_entry:
            type: string
            label: 'Glossary entry value'
          weight:
            type: integer
            label: 'Sort weight'

plugin.plugin_configuration.facets_processor.glossary_custom_order:
  type: mapping
  label: 'Glossary custom sort widget order'
  mapping:
    sort:
      type: string
      label: sort order
