mukurtu_site_settings.design_settings:
  title: 'Color settings'
  route_name: config_pages.design_settings
  description: 'Switch the color palette or set custom colors.'
  parent: mukurtu_dashboard
  menu_name: dashboard-look-feel
