mukurtu_import.mukurtu_import_strategy.*:
  type: config_entity
  label: 'Mukurtu Import Strategy'
  mapping:
    id:
      type: string
      label: 'ID'
    uid:
      type: integer
    label:
      type: label
      label: 'Label'
    description:
      type: string
    target_entity_type_id:
      type: string
      label: 'Target Entity Type ID'
    target_bundle:
      type: string
      label: 'Target Bundle'
    default_format:
      type: string
      label: 'Default Format'
    mapping:
      type: sequence
      sequence:
        type: mapping
        mapping:
          source:
            type: string
          target:
            type: string
